version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - app.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - tailorshop_network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: app.env
    depends_on:
      - database
    networks:
      - tailorshop_network
    ports:
    - "8080:8080"
volumes:
  data:
networks:
  tailorshop_network:
    name: tailorshop_network
    driver: bridge