DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS measures CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products_type CASCADE;
DROP TABLE IF EXISTS products CASCADE;