// Code generated by sqlc. DO NOT EDIT.
// source: measures.sql

package db

import (
	"context"
	"database/sql"
)

const createMeasure = `-- name: CreateMeasure :one
INSERT INTO measures (
  customer_id, name, number
) VALUES (
  $1, $2, $3
)
RETURNING code, customer_id, name, number
`

type CreateMeasureParams struct {
	CustomerID sql.NullInt64  `json:"customerID"`
	Name       sql.NullString `json:"name"`
	Number     sql.NullString `json:"number"`
}

func (q *Queries) CreateMeasure(ctx context.Context, arg CreateMeasureParams) (Measure, error) {
	row := q.db.QueryRowContext(ctx, createMeasure, arg.CustomerID, arg.Name, arg.Number)
	var i Measure
	err := row.Scan(
		&i.Code,
		&i.CustomerID,
		&i.Name,
		&i.Number,
	)
	return i, err
}

const deleteMeasureByCustomerID = `-- name: DeleteMeasureByCustomerID :exec
DELETE FROM measures
WHERE customer_id = $1
`

func (q *Queries) DeleteMeasureByCustomerID(ctx context.Context, customerID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteMeasureByCustomerID, customerID)
	return err
}

const deleteMeasureByID = `-- name: DeleteMeasureByID :exec
DELETE FROM measures
WHERE code = $1
`

func (q *Queries) DeleteMeasureByID(ctx context.Context, code int32) error {
	_, err := q.db.ExecContext(ctx, deleteMeasureByID, code)
	return err
}

const getMeasureByCustomerID = `-- name: GetMeasureByCustomerID :many
SELECT code, customer_id, name, number FROM measures
WHERE customer_id = $1 LIMIT 1
`

func (q *Queries) GetMeasureByCustomerID(ctx context.Context, customerID sql.NullInt64) ([]Measure, error) {
	rows, err := q.db.QueryContext(ctx, getMeasureByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measure
	for rows.Next() {
		var i Measure
		if err := rows.Scan(
			&i.Code,
			&i.CustomerID,
			&i.Name,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasureByID = `-- name: GetMeasureByID :one
SELECT code, customer_id, name, number FROM measures
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetMeasureByID(ctx context.Context, code int32) (Measure, error) {
	row := q.db.QueryRowContext(ctx, getMeasureByID, code)
	var i Measure
	err := row.Scan(
		&i.Code,
		&i.CustomerID,
		&i.Name,
		&i.Number,
	)
	return i, err
}

const listmeasures = `-- name: Listmeasures :many
SELECT code, customer_id, name, number FROM measures
ORDER BY name
`

func (q *Queries) Listmeasures(ctx context.Context) ([]Measure, error) {
	rows, err := q.db.QueryContext(ctx, listmeasures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measure
	for rows.Next() {
		var i Measure
		if err := rows.Scan(
			&i.Code,
			&i.CustomerID,
			&i.Name,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
